### ISSUE TITLE
All calls to kraken-lib should be to shell scripts, not .yaml files

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken#125]
Some <cmd>.go files call K2 shell scripts directly (ex: cmd/helm.go) and others do not (ex: cmd/up.go)

For consistency and maintenance, we should consider rewriting the cmd files to all use the same paradigm if possible.

**Comment by alejandroEsc** [comment]
Interesting point. wonder if its some feasibility issue. Ill check on this soon.

**Comment by alejandroEsc** [comment]
So i would suggest we hold off on this for a bit for two reasons: 
- The code changes are significant and will require significant and breaking changes both upstream in kraken-lib and in kraken itself. Regardless of the paradigm we opt for.
- There are changes planed that will affect how this code works, since it relies heavily on getting current supported versions of the tools, which depend also on the version of k8s installed. These changes will cause both of these codes bases to change anyway.

I suggest when that solution is in place we make these changes.

**Comment by coffeepac** [comment]
what breaking changes would occur if we moved from making direct executions of ansible to shell scripts that execute the ansible?  

I believe that moving all kraken-lib ansible invocations to be the shell scripts is something that will aid in further refactoring as it gives us a single interface (the shell script) that defines how we do something.  if there is a mismatch between the current shell wrapper and some hardcoded ansible invocation then we have a problem that needs to be fixed immediately.

**Comment by alejandroEsc** [comment]
https://github.com/samsung-cnct/kraken-lib/pull/905#issuecomment-338755737 mentions here preference to remove ansible. Taking this as a point towards that direction and we should.
