### ISSUE TITLE
k2cli creates files owned by root:root rather than the current user

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken#31]
The k2cli docker container runs as root creating files in the user's home directory that are owned by root:root.

Files created by an unprivileged user should have the same uid/gid as that user.

**Comment by coffeepac** [comment]
probable solution: pass uid/gid into container and have conatiner code change owner/group to passed in params at completion

**Comment by alejandroEsc** [comment]
After talking to @joejulian about this we have come up with a few conclusions:

- [ ] The easy part is going to be passing the userID:groupID to the container
- [ ] Backwards compatibility will be an issue for the new code, will have to be careful here. I will need another PR that we have pending to merge this.
- [ ] Ansible should not be writing its temp files in $HOME/.ansible/tmp period, we will consider moving this to the /tmp dir of the container. Currently when passing the right --user info the process of bringing up/down a cluster fails because the container claims to have not write priv. to the mentioned volume.
- [ ] The output dir --output will have to be check for writeability and fail if kraken has no right. This is because the fix will be running against previously created files/dirs with root:root ownership/priv.
- [ ] Possibly update documentation to mention the above case and possible solution.
