### ISSUE TITLE
Add commands for cluster updates and scaling

### ISSUE THREAD

**Issue by maratoid** [samsung-cnct/kraken#6]
k2cli cluster upgrade [version] [nodepool name] - update master to latest supported version, update [nodepool name] to [version]

k2cli cluster upgrade [version]  - update master to latest supported version, update all nodepools to [version]

k2cli cluster upgrade - update everything to latest version

k2cli cluster scale [nodepool name] [count] - scale [nodepool name] to [count] instances

**Comment by coffeepac** [comment]
I think this is blocked by https://github.com/samsung-cnct/k2/issues/85, right?

**Comment by coffeepac** [comment]
random note:  we should try to always operate off of the single config file so that the config file remains a source of truth.  

if we do that, it definitely means we need a 'stop and check' moment so we don't, say, upgrade the ASG without doing an update of the cluster nodes.

**Comment by coffeepac** [comment]
this is far away as it represents re-writes to the configuration file because we think the configuration file is the current state

**Comment by alejandroEsc** [comment]
I am a bit confused by this ticket, as I agree that these changes, or commands are equivalent to changing the state of the world and therefore the current config file as it exists. Since the primary state of a cluster is preserved or should be preserved in the config file I think this sort of walks away from that. 

I wonder if we would be best served by suggesting instead a process for updating these things in the config file first (by a person) and then subsequently `re-upping` the cluster so that it matches the changes.
